# nomad-onload .goreleaser.yml
# Copyright (c) 2024 Neomantra BV
# Documentation at http://goreleaser.com

project_name: nomad-onload

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/nomad-device-onload
    id: nomad-device-onload
    binary: nomad-device-onload
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
archives:
  - id: nomad-device-onload
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

universal_binaries:
  - replace: true

release:
  github:
    owner: neomantra
    name: nomad-device-onload
