# Taskfile.yml
# Copyright (c) 2024 Neomantra BV

version: '3'

tasks:
  default:
    cmds:
      - task: build

  clean:
    cmds:
      - rm -f ./bin/nomad-device-onload ./bin/nomad-probe-onload ./bin/launcher

  tidy:
    cmds:
      - go mod tidy

  install-deps:
    deps:
      - tidy
    cmds:
      - go build -o ./bin/launcher github.com/hashicorp/nomad/plugins/shared/cmd/launcher
    generates:
      - ./bin/launcher

  update-deps:
    cmds:
      - go get -u ./...

  build:
    deps:
      - build-plugin
      - build-onload-probe

  eval:
    deps:
      - build-plugin
    cmds:
      - ./bin/launcher device ./bin/nomad-device-onload ./examples/onload-ubuntu.hcl

  build-plugin:
    deps:
      - install-deps
      - tidy
    cmds:
      - go build -o ./bin/nomad-device-onload cmd/nomad-device-onload/*.go
    generates:
      - ./bin/nomad-device-onload
    sources:
      - cmd/nomad-device-onload/*.go
      - internal/**/*.go
    silent: false

  # for testing
  dev-install-plugin:
    deps:
      - build-plugin
    cmds:
      - |
        PLUGIN_DIR=${PLUGIN_DIR:-/local/nomad/plugins}
        sudo mkdir -p ${PLUGIN_DIR}
        sudo cp ./bin/nomad-device-onload ${PLUGIN_DIR}/

  dev-install-plugin-restart-nomad:
    deps:
      - build-plugin
    cmds:
      - |
        PLUGIN_DIR=${PLUGIN_DIR:-/local/nomad/plugins}
        sudo systemctl stop nomad
        sudo mkdir -p ${PLUGIN_DIR}
        sudo cp ./bin/nomad-device-onload ${PLUGIN_DIR}/
        sudo systemctl start nomad

  build-onload-probe:
    deps:
      - tidy
    cmds:
      - go build -o ./bin/nomad-probe-onload cmd/onload-probe/*.go
    generates:
      - ./bin/nomad-probe-onload
    sources:
      - cmd/onload-probe/*.go
      - internal/**/*.go
    silent: false
